# Builds the LaTeX document after changes have been made to source. 
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: notes.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: notes.pdf
